// Generated by tools/build-cli-errors.py from data/errors.json.
// Do not edit. Run the generator; the diff is the review.

export const ERRORS = [
  {
    "code": "535 5.7.139",
    "enhanced": "5.7.139",
    "message": "Authentication unsuccessful, basic authentication is disabled",
    "kind": "auth-refused",
    "scope": "tenant or mailbox",
    "meaning": "Microsoft 365 refused username-and-password authentication. The credentials are almost certainly fine — the authentication *method* is switched off. Retyping the password, generating a new one, or recreating the mailbox will not change anything.",
    "slug": "535-5-7-139-basic-authentication-is-disabled"
  },
  {
    "code": "535 5.7.139",
    "enhanced": "5.7.139",
    "message": "SmtpClientAuthentication is disabled for the Tenant",
    "kind": "auth-refused",
    "scope": "tenant",
    "meaning": "The same refusal, reported at tenant level: the block applies to every mailbox that inherits the tenant setting, not just the one you are testing. Switching to a different mailbox will produce the same error, which is the fastest way to confirm you are in this case rather than the per-mailbox one.",
    "slug": "535-5-7-139-smtpclientauthentication-is-disabled-for-the-tenant"
  },
  {
    "code": "535 5.7.139",
    "enhanced": "5.7.139",
    "message": "SmtpClientAuthentication is disabled for the Mailbox",
    "kind": "auth-refused",
    "scope": "mailbox",
    "meaning": "The same refusal, reported for this one mailbox. Either an admin disabled it explicitly here, or it inherits a tenant-wide block and Microsoft is naming the mailbox rather than the tenant. Common on personal Outlook.com accounts and on single mailboxes that have been locked down deliberately — worth asking why before undoing it.",
    "slug": "535-5-7-139-smtpclientauthentication-is-disabled-for-the-mailbox"
  },
  {
    "code": "535 5.7.3",
    "enhanced": "5.7.3",
    "message": "Authentication unsuccessful",
    "kind": "auth-refused",
    "scope": "tenant or mailbox",
    "meaning": "A generic refusal with the same set of causes as 5.7.139, but without the sub-code that tells you which. Because it names nothing, it is the one most often mistaken for a wrong password. Check the four causes before touching the credentials.",
    "slug": "535-5-7-3-authentication-unsuccessful"
  },
  {
    "code": "535 5.7.57",
    "enhanced": "5.7.57",
    "message": "SMTP; Client was not authenticated to send anonymous mail",
    "kind": "no-credentials",
    "scope": "client",
    "meaning": "A different problem from the ones above: the client sent no credentials at all, or sent them after `MAIL FROM` instead of before. Usually a device or script configured for anonymous internal relay that is now pointed at an endpoint requiring authentication. Check whether the SMTP settings have an authentication checkbox that is switched off, before assuming Basic auth is the issue.",
    "slug": "535-5-7-57-client-was-not-authenticated-to-send-anonymous-mail"
  },
  {
    "code": "550 5.7.60",
    "enhanced": "5.7.60",
    "message": "SMTP; Client does not have permissions to send as this sender",
    "kind": "wrong-sender",
    "scope": "client",
    "meaning": "Authentication succeeded. This is not the Basic auth shutdown. The `From` address in the message does not belong to the mailbox that authenticated, and Microsoft 365 will not let one send as the other without an explicit Send As permission. Common after pointing a device at a shared or service mailbox while leaving the old From address in its settings.",
    "slug": "550-5-7-60-client-does-not-have-permissions-to-send-as-this-sender"
  }
];

export const DEVICE_CODES = {
  "1102": {
    "vendor": "Kyocera",
    "note": "Kyocera MFPs report an SMTP AUTH refusal as send error 1102 (also shown as 0x1102). It looks like a hardware fault and is not one - the device is being refused by the mail server.",
    "kind": "auth-refused"
  }
};
