#!/usr/bin/env python3
"""Generate the README's Contents list from its own headings.

README.md is 311 lines with thirteen sections, and 52 of 55 unique visitors in
the last fortnight landed on it. There was no way to jump. GitHub has an outline
button, but it is an icon most readers never press, and an inline list is also
thirteen internal anchor links - the one ranking signal on this page we control.

Generated rather than written, and for a reason that cost something today: the
error-page index in docs/ERROR-MESSAGES.md was maintained by hand while the
pages beside it were generated, and eleven pages ended up in the sitemap with
nothing linking to them. A contents list is the same shape of thing. It goes
stale silently, because a missing row looks like nothing at all.

    python tools/build-readme-toc.py            # rewrite
    python tools/build-readme-toc.py --check    # fail if it would change
"""

import argparse
import pathlib
import re
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
PLIK = KORZEN / "README.md"
POCZATEK = "<!-- BEGIN GENERATED CONTENTS -->"
KONIEC = "<!-- END GENERATED CONTENTS -->"

# GitHub's anchor rules: lowercase, spaces to hyphens, drop anything that is not
# a letter, digit, hyphen or underscore. Emoji in a heading disappear entirely,
# which is why "## ⭐ Support ZeroSMTP" anchors as #-support-zerosmtp.
def kotwica(tekst):
    """GitHub's own rule, checked against the rendered page rather than assumed.

    Two cases break a naive implementation, and both are in this README:

      "## ⭐ Support ZeroSMTP"      -> #-support-zerosmtp
      "## Security & Deliverability" -> #security--deliverability

    The emoji is removed and leaves the space in front of the word, which
    becomes a leading hyphen. The ampersand is removed and leaves the spaces on
    both sides of it, which become two hyphens. So: do not strip the ends, and
    do not collapse runs of whitespace - each space becomes exactly one hyphen.
    Stripping and collapsing is the obvious implementation and produces two
    dead links out of nine.
    """
    a = tekst.strip().lower()
    a = re.sub(r"[^\w\s-]", "", a, flags=re.UNICODE)
    return a.replace(" ", "-")


def zbuduj(tresc):
    naglowki = [
        m.group(1).strip()
        for m in re.finditer(r"^##[ \t]+(.+)$", tresc, flags=re.M)
    ]
    wiersze = [f"- [{h}](#{kotwica(h)})" for h in naglowki]
    return "\n".join([
        POCZATEK,
        "<!-- Generated by tools/build-readme-toc.py from this file's own",
        "     headings. Do not edit by hand - a contents list that drifts is",
        "     worse than none, because a missing row looks like nothing. -->",
        "",
        "## Contents",
        "",
        *wiersze,
        "",
        KONIEC,
    ])


def pozycje(tresc):
    """Rows inside the generated block only.

    Counting anchors across the whole file reports fifteen for a nine-row list,
    because the header nav already links to #quickstart and #code-examples. A
    count that includes things it did not produce is not a count of anything.
    """
    a = tresc.index(POCZATEK)
    b = tresc.index(KONIEC)
    return re.findall(r"^- \[", tresc[a:b], flags=re.M)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    tresc = PLIK.read_text(encoding="utf-8")
    if POCZATEK not in tresc:
        print(f"::error file=README.md::{POCZATEK} is missing - nothing to "
              f"generate into", file=sys.stderr)
        return 1

    a = tresc.index(POCZATEK)
    b = tresc.index(KONIEC) + len(KONIEC)
    # Built from the file with the old block removed, so the generated list
    # never contains its own "## Contents" heading.
    bez = tresc[:a] + tresc[b:]
    nowy = tresc[:a] + zbuduj(bez) + tresc[b:]

    if args.check:
        if nowy != tresc:
            print("::error file=README.md::Contents is out of date. Run: "
                  "python tools/build-readme-toc.py", file=sys.stderr)
            return 1
        print(f"README Contents matches its headings "
              f"({len(pozycje(nowy))} entries)")
        return 0

    PLIK.write_text(nowy, encoding="utf-8", newline="\n")
    print(f"wrote README.md Contents - {len(pozycje(nowy))} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
